### PR TITLE
fix: handle integer overflow issues when input integer is larger than Int.MAX_VALUE

### LINKED ISSUE #201: [PE-D] "edit -x 4 -d 2147483648" shows "Completion time should be greater than 0" error
"edit -x 4 -d 2147483648" shows "Completion time should be greater than 0" error even though the number 2147483648 is objectively greater than 0

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DaneMarc/ped#5

### PR DESCRIPTION
**Pull request by aidanaden**
Fixes #201 and #184:
- issue: completion time error shows "should be greater than 0" for values that are above int.MAX_VALUE
- solution: set both completion time and serving size as integers and fix upper limits for both (completion time < 1 year in minutes, serving size < 1000 pax)

TODO:
- update: add to UG/DG to remind users that completion time and serving size are both integers and have upper limits (< 1 year for completion time and < 1000 pax for serving size)

### CODE REVIEW

File: src/main/java/seedu/address/model/recipe/CompletionTime.java [hunk 1]
```diff
@@ -28,7 +30,7 @@ public CompletionTime(Integer completionTime) {
     }
 
     public static boolean isValidCompletionTime(Integer test) {
-        return (test > 0);
+        return (test > 0 && test < 525600);
```
Comment (yusufaine) [inline src/main/java/seedu/address/model/recipe/CompletionTime.java:33]: Should the upper bound be inclusive?

File: src/main/java/seedu/address/model/recipe/ServingSize.java [hunk 2]
```diff
@@ -29,7 +30,7 @@ public ServingSize(Integer size) {
      * Checks if the size is a valid Integer value > 0.
      */
     public static boolean isValidServingSize(Integer test) {
-        return test > 0;
+        return (test > 0 && test < 1000);
```
Comment (yusufaine) [inline src/main/java/seedu/address/model/recipe/ServingSize.java:33]: Same thing with this.

**Review by yusufaine — APPROVED** [review]
LGTM, just need clarification on whether the upper-bounds should be inclusive

File: src/main/java/seedu/address/model/recipe/ServingSize.java (hunk 2 above)
Comment (aidanaden) [reply src/main/java/seedu/address/model/recipe/ServingSize.java:33]: idk man does it rly matter?? i think this is quite arbitrary and shouldnt make too big of a difference

Comment (yusufaine) [reply src/main/java/seedu/address/model/recipe/ServingSize.java:33]: Mainly for our UG and what we tell our users the bounds are, and bounds testing. 

Example: "serving size of up to 1000" would mean 1000 is a valid entry but this check makes it such that its only valid if its <1000

File: src/main/java/seedu/address/model/recipe/ServingSize.java [hunk 3]
```diff
@@ -10,7 +10,8 @@
  */
 public class ServingSize {
     public static final String MESSAGE_CONSTRAINTS =
-            "ServingSize size should not be left blank or less than or equals to 0";
+            "ServingSize size should be a valid, reasonable amount of servings that's greater than 0 "
+                    + "and less than 1000 servings (that's literally impossible)";
```
Comment (Oddcorner) [inline src/main/java/seedu/address/model/recipe/ServingSize.java:14]: Maybe saying "(that's literally impossible)" is unnecessary and appears too confrontational. Better to explain in the UG that it's a limitation of our application (To protect itself) rather than a limitation of what's physically possible.

**Review by Oddcorner — APPROVED** [review]
LGTM! 🌮

File: src/main/java/seedu/address/model/recipe/CompletionTime.java (hunk 1 above)
Comment (blaketingyu) [reply src/main/java/seedu/address/model/recipe/CompletionTime.java:33]: I think its good to have an upper bound in case of testers putting in max_int size HAHAHHA @yusufaine

Comment (blaketingyu) [reply src/main/java/seedu/address/model/recipe/CompletionTime.java:33]: 1 year should be more than enough as an upper limit

File: src/main/java/seedu/address/model/recipe/ServingSize.java (hunk 3 above)
Comment (blaketingyu) [reply src/main/java/seedu/address/model/recipe/ServingSize.java:14]: The error message lgtm ah, if im the user, ill laugh. 🌮

**Review by blaketingyu — APPROVED** [review]
LGTM. See whether you wanna make changes the other members are saying but to me, it seems fine 👍

File: src/main/java/seedu/address/model/recipe/CompletionTime.java (hunk 1 above)
Comment (yusufaine) [reply src/main/java/seedu/address/model/recipe/CompletionTime.java:33]: @blaketingyu oh i meant to ask if the condition should be `test <= 525600`, since people would test the boundary

File: src/main/java/seedu/address/model/recipe/ServingSize.java (hunk 3 above)
Comment (yusufaine) [reply src/main/java/seedu/address/model/recipe/ServingSize.java:14]: Can be interpreted either way tbh. I would love it if the users found it funny too but I also can't 100% say that they'll have the same humour

File: src/main/java/seedu/address/model/recipe/CompletionTime.java (hunk 1 above)
Comment (blaketingyu) [reply src/main/java/seedu/address/model/recipe/CompletionTime.java:33]: I think good to have a boundary uh if you ask me. It's like boundary value, equivalence partition stuff

File: src/main/java/seedu/address/model/recipe/ServingSize.java (hunk 3 above)
Comment (aidanaden) [reply src/main/java/seedu/address/model/recipe/ServingSize.java]: Removed it just in case poeple get offended! (buncha pussies)
