### PR TITLE
fix: clear and reset parser not removing the excess space added used to fix previous issues

### LINKED ISSUE #249: [Bug-reset- prompt] No prompts for yes or no
[Bug-reset- prompt] No prompts for yes or no
Severity: Low

Features like `clear` or `reset` do not prompt the user when you do not use the `-f` flag
image
image

Suggestion:
Probably just edit the user guide to say that it's a future feature and change the command result screen

Update: The `reset -f` and `clear -f` features do not work either, if it's not a trivial bug fix then probably can just remove from the user guide?

_Originally posted by @pyk595 in https://github.com/AY2122S2-CS2103T-T17-2/tp/issues/240#issuecomment-1092903352_

### PR DESCRIPTION
**Pull request by aidanaden**
Fixes #249 

Issue: clear and reset command parsers weren't updated to trim the excess " " added that handles issue of users adding invalid arguments that weren't caught by parsers since our tokens expect an excess space at the end.

Fix: adds .trim() functions in clear and reset command parsers

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ClearCommandParser.java [hunk 1]
```diff
@@ -20,7 +20,7 @@
      */
 
     public static boolean isNotForcedClear(String arguments) {
-        return arguments.isEmpty();
+        return arguments.trim().isEmpty();
```
Comment (blaketingyu) [inline src/main/java/seedu/address/logic/parser/ClearCommandParser.java:23]: 🌮

**Review by blaketingyu — APPROVED** [review]
LGTM! Thanks for the fix bruh!

**Review by gigituang — APPROVED** [review]
LGTM: 🌮
