### PR TITLE
fix: FindCommand is now case-insensitive

### LINKED ISSUE #70: bug: FindCommand should be case-insensitive
## Currently
1. `find Western` returns a list of recipes that contain list of recipes that has "Western"
2. `find western` returns an empty list.

## Expected
Point (2) above should return recipes that contain "Western" and "western"

### PR DESCRIPTION
**Pull request by yusufaine**
Closes #70.

### CODE REVIEW

**Review by blaketingyu — APPROVED** [review]
LGTM 🌮 The naming variables are much more clearer as compared to the last time. Other than that, the conversion to lowercase should more or less solve our issue of making our search case sensitive. Good job! 🔥

File: src/main/java/seedu/address/model/recipe/Recipe.java [hunk 1]
```diff
@@ -45,11 +44,9 @@ public Recipe(Name name, CompletionTime completionTime, ServingSize servingSize,
         this.ingredients.addAll(ingredients);
         this.steps.addAll(steps);
         this.tags.addAll(tags);
-        initSearchSet();
+        this.initSearchSet();
```
Comment (aidanaden) [inline src/main/java/seedu/address/model/recipe/Recipe.java:47]: Nice was wondering if i should suggest adding the "this" call since we do it for all private variables/fn calls - now everything's consistent yay

**Review by aidanaden — APPROVED** [review]
LGTM! 🍝 🍝 🍝 lets fkin gOOOOOOOOOOOOO
